services:
  database:
    image: 'postgres:16.1-alpine3.18'
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST_DEV: ${DB_HOST}
      DB_PORT_DEV: ${DB_PORT}
      DB_USER_DEV: ${DB_USER}
      DB_PASS_DEV: ${DB_PASS}
      DB_NAME_DEV: ${DB_NAME}
    ports:
      - '5443:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST_DEV: ${DB_HOST}
      DB_PORT_DEV: ${DB_PORT}
      DB_USER_DEV: ${DB_USER}
      DB_PASS_DEV: ${DB_PASS}
      DB_NAME_DEV: ${DB_NAME}

volumes:
  db_data:
